name: Compile Test

on: 
  pull_request:
    type: [opened, synchronize]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install CMake
        run: sudo apt-get -y install cmake
      - name: Checkout repo
        uses: actions/checkout@v3

      - run: pwd
      - run: ls
      