name: Compile Test

on: 
  pull_request:
    type: [opened, synchronize]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install CMake
        run: sudo apt-get -y install cmake
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make build folder 
        run: mkdir build

      - name: Create makefile and build
        working-directory: ./build
        run: cmake -G "Unix Makefiles" .. && cmake --build .

       - run: cd build && ls
      