name: Compile Test

on: 
  pull_request:
    type: [opened, synchronize]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install CMake
        run: sudo apt-get -y install cmake
      - run: which cmake
      - run: cmake --version
      