name: Compile Test

on: 
  pull_request:
    type: [opened, synchronize]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install CMake
        run: sudo apt-get -y install cmake
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make and move to build folder 
        run: mkdir build && cd build

      - name: Create makefile
        run: cmake -G "Unix Makefiles" ..

      - name: Build project
        run: cmake --build .

      - run: ls
      