name: Compile Test

on: 
  pull_request:
    type: [opened, synchronize]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install CMake
        run: sudo apt-get -y install cmake
      - name: Install Unix Makefiles
        run: sudo apt-get -y install make
      
      - run: which cmake
      - run: cmake --version
      - run: which make
      - run: make --version
      - run: which gcc
      - run: which g++
      